# Generated by Django 5.2.4 on 2025-08-07 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_employee_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("engineering", "Engineering"),
                    ("design", "Design"),
                    ("marketing", "Marketing"),
                    ("sales", "Sales"),
                    ("hr", "Human Resources"),
                    ("finance", "Finance"),
                    ("operations", "Operations"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("developer", "Developer"),
                    ("designer", "Designer"),
                    ("analyst", "Analyst"),
                    ("tester", "Tester"),
                    ("intern", "Intern"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["email"], name="employees_e_email_8f5bbc_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department", "is_active"],
                name="employees_e_departm_c5cc9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["role", "is_active"], name="employees_e_role_3e6dfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["manager", "is_active"], name="employees_e_manager_4f2c90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["is_active", "hire_date"], name="employees_e_is_acti_f30478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_id", "is_active"],
                name="employees_e_employe_6a28c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="employees_e_first_n_597cbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["-created_at"], name="employees_e_created_9cbbc2_idx"
            ),
        ),
    ]
