# Generated by Django 5.2.4 on 2025-08-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("developer", "Developer"),
                    ("designer", "Designer"),
                    ("analyst", "Analyst"),
                    ("tester", "Tester"),
                    ("intern", "Intern"),
                    ("mobiux_employee", "Mobiux Employee"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
