# Generated by Django 5.2.4 on 2025-08-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_update_structure"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employee",
            new_name="employees_e_designa_c97ae9_idx",
            old_name="employees_e_designa_f8a9b2_idx",
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                choices=[
                    ("managing_partner", "Managing Partner"),
                    ("head_of_engineering", "Head of Engineering"),
                    ("head_of_sales", "Head of Sales"),
                    ("business_operations_manager", "Business Operations Manager"),
                    ("business_development_manager", "Business Development Manager"),
                    ("business_consultant", "Business Consultant"),
                    ("business_analyst_intern", "Business Analyst Intern"),
                    ("ai_architect", "AI Architect"),
                    ("principal_engineer", "Principal Engineer"),
                    ("engineering_tech_lead", "Engineering Tech Lead"),
                    ("solutions_architect", "Solutions Architect"),
                    ("sr_software_engineer", "Sr Software Engineer"),
                    ("software_engineer", "Software Engineer"),
                    ("ai_engineer", "AI Engineer"),
                    ("software_developer_intern", "Software Developer Intern"),
                    ("design_lead", "Design Lead"),
                    ("senior_designer", "Senior Designer"),
                    ("designer", "Designer"),
                    ("sr_qa_engineer", "Sr QA Engineer"),
                    ("qa_engineer", "QA Engineer"),
                    ("qa_intern", "QA Intern"),
                    ("hr_admin_manager", "HR & Admin Manager"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
