# Generated by Django 5.2.4 on 2025-08-05 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_employee_id'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24.0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=101)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='projects.project')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='timesheets__employe_662a75_idx'), models.Index(fields=['project', 'date'], name='timesheets__project_20fe53_idx'), models.Index(fields=['date'], name='timesheets__date_f1b81d_idx'), models.Index(fields=['employee', 'project', 'date'], name='timesheets__employe_7c44bb_idx'), models.Index(fields=['-created_at'], name='timesheets__created_f5cc6d_idx')],
                'unique_together': {('employee', 'project', 'date', 'activity_type')},
            },
        ),
    ]
