# Generated by Django 5.2.4 on 2025-08-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0002_add_draft_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="timesheet",
            new_name="timesheets__status_d1d005_idx",
            old_name="timesheets_status_idx",
        ),
    ]
